### ISSUE TITLE
[question] unclosed providersubscription..?

### ISSUE THREAD

**Issue by lucavenir** [AhmedLSayed9/deliverzler#13]
About this line: https://github.com/AhmedLSayed9/deliverzler/blob/59001b77d4a82b5eaa66236a9d659a9bb0506676/test/utils.dart#L54C13-L54C19

Why aren't we, instead, writing:
```dart
final subscription = container.listen(provider, listener.call, fireImmediately: fireImmediately);
addTearDown(subscription.close);
```

I'm curious about the purpose of this choice

**Comment by AhmedLSayed9** [comment]
There's no need to do that as long as you dispose the ProviderContainer.

**Comment by lucavenir** [comment]
Woah, so `container.dispose` cancels _any_ `ProviderSubscription` active?
I didn't know!

Thank you.

**Comment by AhmedLSayed9** [comment]
> Woah, so `container.dispose` cancels _any_ `ProviderSubscription` active? I didn't know!

`container.dispose` will call dispose method of all non-disposed providers, check [this](https://github.com/rrousselGit/riverpod/blob/dd3c7df6a6b309fbd2bd1ed70f9155b8eeefac1a/packages/riverpod/lib/src/framework/scheduler.dart#L119), and the dispose of these providers will close all listened subscriptions, check [this](https://github.com/rrousselGit/riverpod/blob/dd3c7df6a6b309fbd2bd1ed70f9155b8eeefac1a/packages/riverpod/lib/src/framework/element.dart#L929).
