### ISSUE TITLE
i did not understand the scenario

### ISSUE THREAD

**Issue by RoxDevvv** [AhmedLSayed9/deliverzler#14]
Hi, first i would like to thank you for this great app.,

There is something I struggle to understand 
if the upcoming orders can be seen by all drivers and no one can accept them except the driver that set in `deliveryId `field 
so what is the purpose of showing the orders if they are meant for the specific driver 

in my understanding, if an order can be seen by all drivers the first one who confirms could take the order and the order will hidden from other drivers 

otherwise, if the order is meant only for a specific driver then it should be shown only to him 

please clarify the logic for me am getting headache lol 

Thank you

**Comment by RoxDevvv** [comment]
in the Readme you mentioned that 
Home screen will show stream of delivery orders that are ready to be delivered `upcoming `or is delivering onTheWay.
`Any `employee can `see `order details and `deliver `upcoming orders. 

The last part confused me either the code is broken or you meant something else 
cause right now only registered user `deliveryId  ` in database can click deliver button the rest can see but deliver button won't work for them

**Comment by AhmedLSayed9** [comment]
It depends on the business after all but yes, it's rarely needed that a delivery guy can show another one's order in the way.
We should update the stream of orders to filter by deliveryId when the status is OnTheWay.

**Comment by RoxDevvv** [comment]
Yes you are right about onTheWay case that should have a filter 
But my question is different
What an trying to understand is upcoming case
Does anyone can accept the upcoming order or only specific driver can accept

**Comment by AhmedLSayed9** [comment]
What do you meant by `accept`?

**Comment by RoxDevvv** [comment]
When the order in upcoming state 
The order will appear to all drivers 
All They will have cancel or delivery buttons

**Comment by RoxDevvv** [comment]
So does all drivers can press delivery button ? Or what is the scenario in that case

**Comment by AhmedLSayed9** [comment]
Yes. Upcoming order is an order about to be delivered and in that case any driver can decide to take the order.

An onTheWay order (when confirm button is displayed) can only be handled by the person who is delivering. This one can be filtered to be hidden from the other delivery guys.

Unfortunately, there's no direct way for applying an `OR` condition in firebase queries check [this](https://stackoverflow.com/questions/70114416/combining-multiple-firestore-queries-to-get-specific-results-with-pagination/70114565#70114565), as we need to do:
`if ( deliveryStatus==upcoming || (deliveryStatus==onTheWay && deliveryId==userId) )`

I'll filter it at the client side anyway for better understanding.

**Comment by RoxDevvv** [comment]
> Yes. Upcoming order is an order about to be delivered and in that case any driver can decide to take the order.


If that the sinario then it is not working i tested it 
When i click Deliver button nothing happen unless i put the id in the database in deliveryId field

**Comment by RoxDevvv** [comment]
```
`
Future<void> deliverOrder() async {
      final authority = fetchOrderAuthority();

      switch (authority) {
        case (canProceed: _, isEnabled: true):
          final confirmChoice = await OrderDialogs.confirmChoiceDialog(
            context,
            tr(context).doYouWantToDeliverTheOrder,
          );
          if (confirmChoice) {
            final params = UpdateDeliveryStatus(
              orderId: order.id,
              deliveryStatus: DeliveryStatus.onTheWay,
              deliveryId: userId,
            );
            await ref.read(updateDeliveryStatusControllerProvider.notifier).updateStatus(params);
          }
        case _:
          return;
      }
    }
`
```

Authority prevent from talking the order the only one can take it is the one that his id put in database
Please let me know if you didn't understand the issues that am trying to explain

**Comment by RoxDevvv** [comment]
To replicate the issue put an order in database and don't put deliveryId keep it empty 
The order will appear to all drivers but clicking deliver button will do nothing

**Comment by AhmedLSayed9** [comment]
Nice catch :)
The issue is at [this line](https://github.com/AhmedLSayed9/deliverzler/blob/59001b77d4a82b5eaa66236a9d659a9bb0506676/lib/features/home/domain/orders_service.dart#L23), we return false for `enabled` while it enabled should be true/false depend on the loading state. I'll refactor and fix it.

**Comment by AhmedLSayed9** [comment]
It should work as expected now :)

**Comment by RoxDevvv** [comment]
> Nice catch :) The issue is at [this line](https://github.com/AhmedLSayed9/deliverzler/blob/59001b77d4a82b5eaa66236a9d659a9bb0506676/lib/features/home/domain/orders_service.dart#L23), we return false for `enabled` while `enabled` should be true/false depend on the loading state. I'll refactor and fix it.

Yes as i expected however i couldn't fix it cause i wasn't understanding the whole logic haha  

Thank you

**Comment by AhmedLSayed9** [comment]
I've refactored the naming too. I think it should be more clear now.
