### ISSUE TITLE
Implementing a reset password feature enhances user experience and security 

### ISSUE THREAD

**Issue by VIDHIGUPTA17** [AhmedLSayed9/deliverzler#16]
Users often forget their passwords, leading to frustration and a barrier to accessing their accounts. Currently, our web app lacks a straightforward mechanism for users to reset their passwords independently.

Implement a user-friendly "Forgot Password" feature that allows users to reset their passwords easily. This feature should include:

A "Forgot Password?" link on the login page.
Upon clicking the link, users should be prompted to enter their email address associated with their account.
After entering their email, users should receive a password reset link via email.
The email should contain a secure, time-limited link allowing users to reset their password.
Upon clicking the reset link, users should be directed to a page where they can set a new password securely.

**Comment by AhmedLSayed9** [comment]
> Users often forget their passwords, leading to frustration and a barrier to accessing their accounts. Currently, our web app lacks a straightforward mechanism for users to reset their passwords independently.
> 
> Implement a user-friendly "Forgot Password" feature that allows users to reset their passwords easily. This feature should include:
> 
> A "Forgot Password?" link on the login page. Upon clicking the link, users should be prompted to enter their email address associated with their account. After entering their email, users should receive a password reset link via email. The email should contain a secure, time-limited link allowing users to reset their password. Upon clicking the reset link, users should be directed to a page where they can set a new password securely.

Of course, you should implement a reset password in a real life app.
This is a demo app of a delivery app (that should be part of other apps like client/vendor apps) :)
