### ISSUE TITLE
error: Target of URI doesn't exist: 'package:deliverzler/firebase_options.dart'. (uri_does_not_exist at [deliverzler] lib\core\services\init_services\services_initializer.dart:12)

### ISSUE THREAD

**Issue by Mert-Zengin** [AhmedLSayed9/deliverzler#2]
can you share the file

**Comment by AhmedLSayed9** [comment]
This file can't be shared you have to generate it using your firebase account. Follow these instructions:

1- Create project in Firebase console
2- Install Firebase CLI [here](https://firebase.google.com/docs/cli)
3- run dart pub global activate flutterfire_cli in your Flutter project
4- run flutterfire configure
This will start a command line interface for you to select the Firebase projects you want to link to the Flutter project. After you complete this, a firebase_options.dart file will be generated in your lib/ folder.
