### ISSUE TITLE
-nullsafety.2

### ISSUE THREAD

**Issue by MesharSuliman** [AhmedLSayed9/deliverzler#3]
where is -nullsafety.2

**Comment by MesharSuliman** [comment]
also 
import GoogleMaps
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GMSServices.provideAPIKey("-")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

**Comment by AhmedLSayed9** [comment]
Of course, You'll have to add your firebase and google map configuration.
Also, The application is using null safety. What issue do you exactly face?

**Comment by MesharSuliman** [comment]
Zone

**Comment by MesharSuliman** [comment]
I think 2 app 👎

**Comment by MesharSuliman** [comment]
See https://github.com/MesharSuliman/Login-Flutter-Firebase-**Multi**

**Comment by AhmedLSayed9** [comment]
Please if you've any issue just describe it clearly. I'll close this for now.
