### ISSUE TITLE
Firebase store database model

### ISSUE THREAD

**Issue by Mert-Zengin** [AhmedLSayed9/deliverzler#4]
Can you share database model for use

**Comment by AhmedLSayed9** [comment]
Sure.
![1](https://user-images.githubusercontent.com/70890146/158181103-61089921-8783-4e68-b894-f87012cea978.PNG)
![2](https://user-images.githubusercontent.com/70890146/158181273-9e64632c-70d9-4dd4-b499-9f221488db17.PNG)
