### ISSUE TITLE
Co Developer!

### ISSUE THREAD

**Issue by Tolulope05** [AhmedLSayed9/deliverzler#7]
Hey Man! 
Great work youve got here
Im tryna get to make your app work on my device but i keep getting numerous errors after downloding the zip and running pub get.
any ide on how this might work?
I would love to build on this.
Thanks and ill await your reply.
TOLUCODES

**Comment by AhmedLSayed9** [comment]
You welcome.
Please follow `Instructions to run the project` at ReadMe.

**Comment by AhmedLSayed9** [comment]
There was naming conflict in `currentuserProvider`. Try to use last committed version.

**Comment by Tolulope05** [comment]
Okay i will

**Comment by Tolulope05** [comment]
Thanks
