### ISSUE TITLE
Infrastructure stream exceptions are passed to presentation layer directly

### ISSUE THREAD

**Issue by michaelsoliman1** [AhmedLSayed9/deliverzler#9]
Hi again!

So as you notice here, the body callback will return a stream, and the try/catch are only guarding any exceptions outside of the stream, not the stream itself. meaning that any error occurs inside the stream itself will still be part of the stream (in the form of Stream.error),and will be catched through `onError` listener, or converted to `AsyncError` with `StreamProvider`
<img width="602" alt="image" src="https://github.com/AhmedLSayed9/deliverzler/assets/40867495/c6756bc7-773b-4590-a3f3-39b0dec7b190">

For example, as it's used here, the `_streamTryCatchWrapper` will catch exceptions the code inside the callback will throw (null assertions or argument errors for example),
but it will not catch and map the errors inside the stream (`reference.snapshots()` here), and the same stream is returned directly to the presentation layer to be consumed by providers. So, if a Firestore exception occurred for any reason, say document not found, this error will be the one converted to AsyncError.
<img width="602" alt="image" src="https://github.com/AhmedLSayed9/deliverzler/assets/40867495/e893660f-28bb-4118-98b1-ade33b76ec67">

This will have two main issues
1- we know implementation details from `infra/data layer` we should not know
2- the user will see technical error messages that's will not make sense to him

I'll try to make reproducible example but i don't have the latest dart/flutter version yet.

**Comment by michaelsoliman1** [comment]
I've found a solution to map firestore stream errors to our domain logic errors, although i'm not sure if does it correctly. here is an [example)(https://dartpad.dev/?id=acda70b11175c0ba4a070e6d6c14aed2)

```dart
void main() {
  _thirdPartyStream().handleError((e) {
    if(e is ThirdPartyException){
      throw DomainException();
    }
  }).listen((i) {
    print(i);
  }, onError: (e, s) {
    print(e); // prints DomainException
  });
}

Stream<int> _thirdPartyStream() async* {
  for(int i =0;i<10;i++){
    if(i == 5){
      yield* Stream.error(ThirdPartyException());
    }
    yield i;
  }
}

class ThirdPartyException implements Exception {
  @override
  toString(){
    return 'ThirdPartyException';
  }
}

class DomainException implements Exception {
  @override
  toString(){
    return 'DomainException';
  }
}
```
now we can map firebase stream error the same way
```dart
Stream<T> _streamTryCatchWrapper<T>(Stream<T> Function() body) {
    try {
      return body().handleError((e) {
         throw e.firebaseErrorToServerException();
      });
    } on Exception catch (e) {
      // we should also return stream.error here, not throwing the error, i don't know if riverpod handle thrown exceptions in `StreamProviders` or not 
      return Stream.error(e.firebaseErrorToServerException());
    }
  }
```

**Comment by AhmedLSayed9** [comment]
Oh nice catch!

The thing is, try/catch catches all errors whether error event from the stream or from the function, but it needs an `await` to work for async calls.

i.e: Inside my `_tryCatchWrapper` for Future calls, if you removed "await", errors will not be caught by the wrapper too.

I think we can remove try/catch anyway as it's already handled by riverpod to catch other runtime errors, so we can just do:
```dart
  Stream<T> _streamTryCatchWrapper<T>(Stream<T> Function() body) {
    return body().handleError((e) {
      throw e.firebaseErrorToServerException();
    });
  }
```

**Comment by michaelsoliman1** [comment]
Regarding the first point, try/catch would work if we used `await for` to listen for the stream, but it would terminate the stream in case of any error, and we definitely don't want that.

Continuing on the first example, if we used `await for`, like the following, the stream will stop 4, but when using `listen`, it will continue on with the stream, even in case of errors.
```dart
try {
    await for (var i in _thirdPartyStream()){
      print(i);
    }
  } catch (e) {
    print(e);
  }
// prints 
// 0
// 1
// 2
// 3
// 4
// ThirdPartyException
```

<br>
As for the second point, the try/catch is important here imho (as `body` callback might throw any unhandled exceptions, like null assertions), so we would want to return a generic error message instead of `null assertion used on a null value`. It gives us extra safety and better ux.

**Comment by AhmedLSayed9** [comment]
> Regarding the first point, try/catch would work if we used `await for` to listen for the stream, but it would terminate the stream in case of any error, and we definitely don't want that.
> 
> Continuing on the first example, if we used `await for`, like the following, the stream will stop 4, but when using `listen`, it will continue on with the stream, even in case of errors.

Yes I get that, handleError is needed so the stream doesn't get terminated.

> As for the second point, the try/catch is important here imho (as `body` callback might throw any unhandled exceptions, like null assertions), so we would want to return a generic error message instead of `null assertion used on a null value`. It gives us extra safety and better ux.

UI won't show any unhandled error message anyway, check: https://github.com/AhmedLSayed9/deliverzler/blob/8be5fda817caddb5ec1725a06f03e77db7da0a14/lib/core/presentation/extensions/app_error_extension.dart#L6  Any unhandled error will show as nice "Unexpected error occurred" but the actual error is emitted so I can report it to Crashlytics or something and know what exactly occurred. What do you think?

**Comment by michaelsoliman1** [comment]
Yes that's exactly what i meant, but i would keep the try/catch anyway, for extra safety and to gain more control over the returned errors, and we can always rethrow the exception if needed.

**Comment by AhmedLSayed9** [comment]
> Yes that's exactly what i meant, but i would keep the try/catch anyway, for extra safety and to gain more control over the returned errors, and we can always rethrow the exception if needed.

Riverpod is already doing a try/catch so there's no point to add it unless you want to handle some specific errors and map it to some type of exception, which is not the case here.

**Comment by AhmedLSayed9** [comment]
I'll end up doing this, which is useless:
```dart
Stream<T> _streamTryCatchWrapper<T>(Stream<T> Function() body) {
    try {
      return body().handleError((e) {
         throw e.firebaseErrorToServerException();
      });
    } on Exception catch (e) {
      rethrow;
    }
  }
```
